title : Women in Tech

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: women-in-tech
destination: women-in-tech

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 25
paginate_path: "/updates/page:num"

production_url : http://women-in-tech.apievangelist.com

BASE_PATH : http://women-in-tech.apievangelist.com

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
