version: "3.8"

services:

  ##############################
  # Base de données MariaDB
  ##############################
  women-in-tech-mariadb:
    image: mariadb:10.5
    container_name: women-in-tech-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "$DB_ROOT_PASSWORD"
      MYSQL_DATABASE: "$DB_NAME"
      MYSQL_USER: "$DB_USER"
      MYSQL_PASSWORD: "$DB_PASSWORD"
    ports:
      - "3309:3306"
    volumes:
      # Persistance des données
      - ./mariadb_data:/var/lib/mysql

      # Script SQL lancé au démarrage
      - ./DATA/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - women-in-tech-network

  ##############################
  # PhpMyAdmin
  ##############################
  women-in-tech-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: women-in-tech-phpmyadmin
    environment:
      PMA_HOST: "$DB_HOST"
      PMA_PORT: "$DB_PORT"
      PMA_USER: "$DB_USER"
      PMA_PASSWORD: "$DB_PASSWORD"
    ports:
      - "8088:80"
    networks:
      - women-in-tech-network


  ##############################
  # BACKEND
  ############################
  women-in-tech-backend:
    # Ce service va utiliser l'image Docker créée à partir du Dockerfile
    build:
      context: .
      dockerfile: ./Docker/Backend-Dockerfile
    container_name: women-in-tech-backend

    # Fichier d'environnement
    env_file:
      - .env.docker

    # On expose le port 5000 du conteneur vers le port 5001 de la machine hôte
    ports:
      - "5000:5000"

    # Volumes pour monter les fichiers de l'application Node.js (placés dans le dossier BACKEND)
    volumes:
      # Dossier de l'app
      - ./BACKEND:/app
      # Fichier d'environnement
      - ./.env.docker:/app/.env.docker
      # On monte le dossier node_modules pour éviter de réinstaller les dépendances à chaque redémarrage du conteneur
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # Commande exécutée au démarrage du service
    command: sh -c "npm install && nodemon index.js"
    networks:
      - women-in-tech-network



networks:
  women-in-tech-network:
    driver: bridge
